Marking the package as unsupported on 64-bit Windows until the following 'R CMD build' error (seen on gewurz since the beginning of the 64-bit Windows builds) is addressed:
  * creating vignettes ... ERROR
  ...
  Error: processing vignette 'BGmix.Rnw' failed with diagnostics:
   chunk 6 
  Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
    scan() expected 'a real', got '-1.#IND'
  Execution halted